name: cake-lie

services:
  db:
    image: postgres:17.6-alpine
    restart: unless-stopped
    command: |
      postgres
      -c max_connections=200
      -c shared_buffers=2GB
      -c wal_level=minimal
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
      -c work_mem=16MB
      -c max_wal_senders=0
      -c wal_level=minimal
      -c wal_writer_delay=5s
      -c wal_buffers=32MB
      -c maintenance_work_mem=128MB
      -c max_wal_size=3GB
      -c shared_preload_libraries=pg_stat_statements,auto_explain
      -c auto_explain.log_min_duration=50ms
      -c auto_explain.log_analyze=true
      -c auto_explain.log_buffers=true
      -c auto_explain.log_timing=true
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: localdevuser
      POSTGRES_PASSWORD: localdevuser
      POSTGRES_DB: moresleeplocal
      TZ: Europe/Oslo
    healthcheck:
      test: [ "CMD" , "/usr/local/bin/pg_isready", "-d", "moresleeplocal", "-U", "localdevuser", "-t", "3" ]
      retries: 3
      timeout: 1m
      start_period: 15s

  moresleep:
    image: ghcr.io/javabin/moresleep:edge
    ports:
      - "8082:8082"
    env_file:
      - path: ./.env.moresleep
        required: false
    environment:
      DBHOST: db
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg-data: {}
